# Generated by Django 4.1.3 on 2023-04-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('type', models.TextField(choices=[('unknown', 'Unknown'), ('public', 'Public'), ('private', 'Private')], default=('unknown', 'Unknown'), verbose_name='Type')),
                ('address', models.JSONField(default=dict)),
                ('setting', models.CharField(max_length=100, verbose_name='Setting')),
                ('webpage', models.URLField(blank=True, max_length=100, null=True, verbose_name='Webpage')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_schools', to='school_rating.rating', verbose_name='School Rating')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_ratings', to='school_rating.school', verbose_name='School Rating')),
            ],
            options={
                'verbose_name': 'School Rating',
                'verbose_name_plural': 'School Ratings',
                'db_table': 'school_rating',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='school_rating.school', verbose_name='School')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
            },
        ),
    ]
