# Generated by Django 4.1.3 on 2023-07-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'CommentLike', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['id'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelTable(
            name='commentlike',
            table='comment_like',
        ),
    ]
