# Generated by Django 4.1.3 on 2023-04-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_rating', '0002_alter_commentlike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
    ]
