# Generated by Django 4.1.3 on 2023-05-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_rating', '0003_alter_commentlike_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tuition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tuition'),
        ),
    ]
