# Generated by Django 4.1.3 on 2023-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_rating', '0004_school_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/school/'),
        ),
    ]
