# Generated by Django 4.1.3 on 2023-05-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_rating', '0005_school_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
