# Generated by Django 4.1.3 on 2023-07-21 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_rating', '0007_school_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_likes', to='school_rating.school', verbose_name='comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SchoolLike',
                'verbose_name_plural': 'SchoolLikes',
                'db_table': 'school_like',
            },
        ),
    ]
